// Types for NutriVita app

import type { GlucoseUnit } from "@/lib/glucose-units"

export type { GlucoseUnit }

export type Language = "fr" | "ar" | "en"

export interface User {
  id: string
  name: string
  email?: string
  age: number
  height: number // cm
  weight: number // kg
  sex: "male" | "female" | "other"
  /** Multi-select goals. Primary calorie goal derived: "lose" | "gain" → adjust TDEE; "diabetes" → isDiabetic=true */
  goals: string[]
  activityLevel: 1 | 2 | 3 | 4 | 5
  targetCalories: number
  macros: {
    carbs: number // percentage
    protein: number // percentage
    fat: number // percentage
  }
  units: {
    weight: "kg" | "lbs"
    height: "cm" | "ft"
    glucose: GlucoseUnit
    energy: "kcal" | "kJ"
  }
  /** Glucose target range stored in mg/dL */
  glucoseTarget: { low: number; high: number }
  /** Hide glucose features when false */
  isDiabetic: boolean
  language: Language
  darkMode: boolean
  streak: number
}

export interface FoodItem {
  id: string
  name: string
  nameAr?: string
  nameEn?: string
  cuisine: string
  calories: number // per 100g
  protein: number // g per 100g
  carbs: number // g per 100g
  fat: number // g per 100g
  fiber?: number
  sugar?: number
  sodium?: number
  source: "nutrivita" | "ciqual" | "usda" | "estimated"
  isFavorite?: boolean

  // Micronutriments optionnels (CIQUAL) — null = donnée inconnue (≠ 0)
  vit_c_mg?: number | null      // Vitamine C (mg/100g)
  vit_d_ug?: number | null      // Vitamine D (µg/100g)
  b9_ug?: number | null         // Folates B9 (µg/100g)
  b12_ug?: number | null        // Vitamine B12 (µg/100g)
  iron_mg?: number | null       // Fer (mg/100g)
  calcium_mg?: number | null    // Calcium (mg/100g)
  magnesium_mg?: number | null  // Magnésium (mg/100g)
  zinc_mg?: number | null       // Zinc (mg/100g)
}

export interface MealEntry {
  id: string
  foodId: string
  food: FoodItem
  amount: number // grams
  mealType: "breakfast" | "lunch" | "snack" | "dinner"
  date: string // YYYY-MM-DD
  createdAt: string
}

export interface DailyLog {
  date: string // YYYY-MM-DD
  meals: MealEntry[]
  weight?: number
  waterIntake: number // glasses
  totalCalories: number
  totalProtein: number
  totalCarbs: number
  totalFat: number
}

export interface WeightEntry {
  date: string
  weight: number
  bodyFat?: number
  muscleMass?: number
}

export interface GlucoseReading {
  id: string
  /** Always stored in mg/dL internally (AL-04). */
  value: number
  timestamp: string
  type: "fasting" | "pre-meal" | "post-meal" | "pontuelle" | "cgm"
  source: "manual" | "libreview"
}

export interface ActivityEntry {
  id: string
  type: string
  duration: number // minutes
  caloriesBurned: number
  date: string
  source: "manual" | "strava" | "voice"
  createdAt: string
}

export interface GlucoseStats {
  gmi: number
  tir: number
  cv: number
  average: number
  min: number
  max: number
  distribution: {
    veryLow: number
    low: number
    inRange: number
    high: number
    veryHigh: number
  }
}

export interface Meal {
  type: "breakfast" | "lunch" | "snack" | "dinner"
  name: string
  nameFr: string
  nameAr: string
  nameEn: string
}

export const MEALS: Meal[] = [
  { type: "breakfast", name: "breakfast", nameFr: "Petit-déjeuner", nameAr: "الفطور", nameEn: "Breakfast" },
  { type: "lunch",     name: "lunch",     nameFr: "Déjeuner",        nameAr: "الغداء", nameEn: "Lunch" },
  { type: "snack",     name: "snack",     nameFr: "Collation",       nameAr: "وجبة خفيفة", nameEn: "Snack" },
  { type: "dinner",    name: "dinner",    nameFr: "Dîner",           nameAr: "العشاء", nameEn: "Dinner" },
]

/** AL-08 / EB-04 — Scanned product from barcode. */
export interface ScannedProduct {
  barcode: string
  name: string
  nutriScore: "A" | "B" | "C" | "D" | "E" | null
  score: number // 0–100 (AL-08)
  verdict: "Excellent" | "Médiocre" | "Mauvais"
  additives: string[] // e.g. ["E150d", "E471"]
  timesThisMonth: number
  sucres?: number  // g per 100g
  sel?: number     // g per 100g
  ags?: number     // g per 100g (acides gras saturés)
}

// Sample food database (no emojis — IDs are stable)
// Micronutriment values (mg or µg per 100g) from CIQUAL 2020 / ANSES estimates.
// null = donnée inconnue dans CIQUAL (≠ 0).
export const SAMPLE_FOODS: FoodItem[] = [
  {
    id: "1",  name: "Laban", nameAr: "لبن", nameEn: "Laban",
    cuisine: "Maghreb", calories: 63, protein: 3.5, carbs: 4.8, fat: 3.2, source: "nutrivita",
    vit_c_mg: 1.0, vit_d_ug: 0.04, b9_ug: 5.0, b12_ug: 0.4,
    iron_mg: 0.05, calcium_mg: 120, magnesium_mg: 11, zinc_mg: 0.4,
  },
  {
    id: "2",  name: "Pain complet", nameAr: "خبز كامل", nameEn: "Whole wheat bread",
    cuisine: "Française", calories: 262, protein: 9, carbs: 49, fat: 3.4, source: "ciqual",
    vit_c_mg: 0, vit_d_ug: null, b9_ug: 27, b12_ug: null,
    iron_mg: 2.5, calcium_mg: 25, magnesium_mg: 58, zinc_mg: 1.8,
  },
  {
    id: "3",  name: "Couscous royal", nameAr: "كسكس ملكي", nameEn: "Royal couscous",
    cuisine: "Maghreb", calories: 178, protein: 12, carbs: 22, fat: 5, source: "nutrivita",
    vit_c_mg: null, vit_d_ug: null, b9_ug: null, b12_ug: null,
    iron_mg: null, calcium_mg: null, magnesium_mg: null, zinc_mg: null,
  },
  {
    id: "4",  name: "Salade niçoise", nameAr: "سلطة نيسواز", nameEn: "Niçoise salad",
    cuisine: "Française", calories: 285, protein: 18, carbs: 12, fat: 22, source: "ciqual",
    vit_c_mg: 12, vit_d_ug: 1.2, b9_ug: 40, b12_ug: 1.0,
    iron_mg: 2.0, calcium_mg: 80, magnesium_mg: 28, zinc_mg: 1.0,
  },
  {
    id: "5",  name: "Tajine poulet", nameAr: "طاجين دجاج", nameEn: "Chicken tagine",
    cuisine: "Maghreb", calories: 195, protein: 22, carbs: 8, fat: 9, source: "nutrivita",
    vit_c_mg: null, vit_d_ug: null, b9_ug: null, b12_ug: null,
    iron_mg: null, calcium_mg: null, magnesium_mg: null, zinc_mg: null,
  },
  {
    id: "6",  name: "Croissant", nameAr: "كرواسون", nameEn: "Croissant",
    cuisine: "Française", calories: 406, protein: 8, carbs: 45, fat: 21, source: "ciqual",
    vit_c_mg: 0, vit_d_ug: 0.3, b9_ug: 32, b12_ug: 0.2,
    iron_mg: 1.2, calcium_mg: 23, magnesium_mg: 16, zinc_mg: 0.6,
  },
  {
    id: "7",  name: "Riz blanc", nameAr: "أرز أبيض", nameEn: "White rice",
    cuisine: "International", calories: 130, protein: 2.7, carbs: 28, fat: 0.3, source: "ciqual",
    vit_c_mg: 0, vit_d_ug: null, b9_ug: 2, b12_ug: null,
    iron_mg: 0.2, calcium_mg: 3, magnesium_mg: 13, zinc_mg: 0.6,
  },
  {
    id: "8",  name: "Huile d'olive", nameAr: "زيت الزيتون", nameEn: "Olive oil",
    cuisine: "Méditerranée", calories: 884, protein: 0, carbs: 0, fat: 100, source: "ciqual",
    vit_c_mg: 0, vit_d_ug: 0, b9_ug: 0, b12_ug: 0,
    iron_mg: 0.4, calcium_mg: 1, magnesium_mg: 0, zinc_mg: 0,
  },
  {
    id: "9",  name: "Poulet grillé", nameAr: "دجاج مشوي", nameEn: "Grilled chicken",
    cuisine: "International", calories: 165, protein: 31, carbs: 0, fat: 3.6, source: "ciqual",
    vit_c_mg: 0, vit_d_ug: 0.1, b9_ug: 7, b12_ug: 0.3,
    iron_mg: 0.8, calcium_mg: 11, magnesium_mg: 27, zinc_mg: 1.6,
  },
  {
    id: "10", name: "Omelette", nameAr: "أومليت", nameEn: "Omelette",
    cuisine: "Française", calories: 154, protein: 11, carbs: 1, fat: 12, source: "ciqual",
    vit_c_mg: 0, vit_d_ug: 1.8, b9_ug: 30, b12_ug: 1.2,
    iron_mg: 1.7, calcium_mg: 55, magnesium_mg: 12, zinc_mg: 1.3,
  },
]

// Translations
export const translations = {
  fr: {
    // Navigation
    journal: "Journal",
    meals: "Repas",
    stats: "Bilan",
    glucose: "Glycémie",
    settings: "Réglages",
    home: "Accueil",
    groceries: "Courses",
    add: "Ajouter",

    // Journal / Home
    greeting: "Bonjour",
    streak: "jours de suite",
    remaining: "restantes",
    over: "au-dessus",
    carbs: "Glucides",
    protein: "Protéines",
    fat: "Lipides",
    weight: "Poids",
    vsYesterday: "vs hier",
    todayMeals: "Aujourd'hui",
    hydration: "Hydratation",
    glasses: "verres",
    activity: "Activité",
    stravaSource: "Strava",

    // Quick actions
    voice: "Vocal",
    photo: "Photo",
    scanner: "Scanner",
    favorites: "Favoris",
    copyYesterday: "Copier hier",

    // Meals
    breakfast: "Petit-déjeuner",
    lunch: "Déjeuner",
    snack: "Collation",
    dinner: "Dîner",
    addFood: "Ajouter",

    // Add sheet
    addMeal: "Ajouter",
    recentFoods: "Récents",
    detectByPhoto: "L'IA détecte le plat",
    sayMeal: "J'ai mangé...",
    barcode: "Code-barres",
    searchCiqual: "Base CIQUAL",
    comingSoon: "Bientôt disponible",
    detectedAt: "Détecté à",
    estimatedPortion: "Portion estimée",
    ingredients: "Ingrédients",
    addToLunch: "Ajouter au déjeuner",

    // Food search
    searchFood: "Rechercher un aliment...",
    search: "Recherche",
    recentlyAdded: "Récemment ajoutés",
    all: "Tous",
    yourFavorites: "Vos favoris",
    searchResults: "Résultats",
    addToMeal: "Ajouter au",
    portion: "Portion",
    customize: "Personnaliser",

    // Stats
    today: "Aujourd'hui",
    days7: "7 jours",
    days30: "30 jours",
    year: "Année",
    weekSummary: "Bilan semaine",
    average: "Moyenne",
    bestDay: "Meilleur jour",
    hardestDay: "Jour difficile",
    weightLost: "Poids perdu",
    muscleGained: "Muscle gagné",
    fatLost: "Graisse",
    bodyFat: "Masse grasse %",
    muscleMass: "Masse musculaire",
    forbesEstimate: "Estimation par formule — ne remplace pas une analyse médicale",
    export: "Exporter",
    exportDone: "Export téléchargé",
    weightEvolution: "Évolution du poids",
    caloriesPerDay: "Calories par jour",
    macroBreakdown: "Répartition macros",
    glucoseSummary: "Glycémie",
    inTarget: "dans la cible",
    deficiencies: "Carences potentielles",
    deficiencyDisclaimer: "Estimation indicative — ne remplace pas un bilan sanguin",
    probable: "Probable",
    toMonitor: "À surveiller",
    insufficientGlucoseData: "Données insuffisantes",

    // Glucose
    glucoseTracking: "Glycémie",
    glucoseDisclaimer: "Indicateur de tendance — ne remplace pas un avis médical",
    last14Days: "14 derniers jours",
    gmi: "GMI",
    estimatedHba1c: "HbA1c estimé",
    tir: "TIR",
    targetRange: "70–180 mg/dL",
    cv: "CV",
    stability: "Stabilité",
    stable: "Stable",
    mean: "Moyenne",
    veryLow: "Très basse",
    low: "Basse",
    target: "Cible",
    high: "Haute",
    veryHigh: "Très haute",
    addReading: "Ajouter",
    importCsv: "Importer LibreView",
    measurements: "mesures",
    hypoAlert: "épisode(s) de glycémie < 54 mg/dL détecté(s) sur la période",
    noGlucoseData: "Aucune mesure sur cette période",
    addFirstReading: "Ajouter une mesure",
    fasting: "À jeun",
    preMeal: "Avant repas",
    postMeal: "Après repas",
    pontuelle: "Ponctuelle",
    contextStats: "Moyennes par contexte",
    periodLabel7d: "7 jours",
    periodLabel14d: "14 jours",
    periodLabel30d: "30 jours",

    // Settings
    profile: "Profil",
    edit: "Modifier",
    objective: "Objectif",
    recommended: "recommandés",
    units: "Unités de mesure",
    macroGoals: "Objectifs macros",
    appearance: "Apparence",
    darkMode: "Mode sombre",
    language: "Langue",
    data: "Données",
    databaseSize: "Taille base de données",
    lastSync: "Dernière sync Strava",
    clearJournal: "Effacer le journal",
    clearWeight: "Effacer les données poids",
    clearGlucose: "Effacer les données glycémie",
    exportData: "Exporter mes données (RGPD)",
    deleteAccount: "Supprimer mon compte",
    integrations: "Intégrations",
    connected: "Connecté",
    notConnected: "Non connecté",
    disconnect: "Déco.",
    notAvailable: "Non disponible",
    about: "À propos",
    privacyPolicy: "Politique de confidentialité",
    legalNotice: "Mentions légales",
    rateApp: "Évaluer l'app",
    healthGroup: "Santé",
    glucoseTargetLabel: "Cible glycémique",
    diabeticToggle: "Je suis diabétique",
    diabeticToggleHint: "Affiche les fonctions glycémie dans l'app",
    confirmDelete: "Confirmer la suppression",
    irreversible: "Cette action est irréversible.",
    deleteAccountConfirm: "Êtes-vous sûr de vouloir supprimer votre compte ? Toutes vos données seront définitivement supprimées.",
    saveProfile: "Enregistrer",
    profileEdit: "Modifier le profil",
    logout: "Se déconnecter",
    logoutTitle: "Se déconnecter ?",
    logoutDesc: "Vous devrez vous reconnecter pour accéder à vos données.",
    clearAction: "Effacer",

    // Goals
    loseWeight: "Perdre du poids",
    maintainWeight: "Maintenir mon poids",
    gainMuscle: "Prendre du muscle",
    manageDiabetes: "Gérer mon diabète",

    // Voice
    speakNow: "Parlez maintenant...",
    analyzing: "Analyse en cours...",
    serverWaking: "Réveil du serveur en cours...",
    offlineBanner: "Hors ligne — données locales affichées",
    loadingData: "Chargement...",
    retryLoad: "Réessayer",
    errorLoading: "Erreur de chargement",
    scanProduct: "Scanner un produit",
    detectedFoods: "Aliments détectés",
    cancel: "Annuler",
    total: "Total",

    // Activity
    addActivity: "Ajouter une activité",
    duration: "Durée",
    caloriesBurned: "kcal brûlées",
    activityType: "Type d'activité",
    todayActivity: "Activité du jour",
    voiceActivity: "Activité vocale",
    speakActivity: "Dites par ex. : \"30 minutes de course\"",
    noActivity: "Aucune activité ajoutée",

    // Groceries
    myGroceries: "Mes courses",
    monthlyOverview: "Bilan du mois",
    addedSugars: "Sucres ajoutés",
    salt: "Sel",
    saturatedFat: "Graisses saturées",
    vsOmsReference: "vs repère OMS",
    riskAdditives: "additif(s) à risque ce mois-ci",
    presentIn: "présents dans",
    products: "produits",
    scannedProducts: "Produits scannés",
    seeAlternatives: "Voir des alternatives plus saines",
    timesThisMonth: "×",
    excellent: "Excellent",
    mediocre: "Médiocre",
    bad: "Mauvais",

    // Onboarding
    welcome: "Bienvenue sur NutriVita",
    tagline: "Votre compagnon nutrition intelligent",
    getStarted: "Commencer",
    tellUs: "Parlez-nous de vous",
    firstName: "Prénom",
    age: "Âge",
    years: "ans",
    sex: "Sexe",
    male: "Homme",
    female: "Femme",
    other: "Autre",
    height: "Taille",
    yourGoal: "Votre objectif",
    activityLevel: "Niveau d'activité",
    sedentary: "Sédentaire",
    lightlyActive: "Peu actif",
    moderatelyActive: "Modérément actif",
    veryActive: "Très actif",
    extraActive: "Extrêmement actif",
    ready: "C'est parti !",
    dailyGoal: "Objectif",
    perDay: "/jour",
    startJourney: "Commencer mon parcours",
    diabeticQuestion: "Suivez-vous votre glycémie ?",
    diabeticYes: "Oui, j'active le suivi glycémique",
    diabeticNo: "Non, passer cette étape",

    // Landing
    heroTitle: "Comprenez ce que vous mangez, en une photo",
    heroSubtitle: "Photo, voix, calories, poids, glycémie et courses — en FR, عربي et EN",
    startFree: "Commencer gratuitement",
    proSpace: "Espace praticien",
    dataProtected: "Données protégées · RGPD",
    proTabTitle: "Espace professionnel",
    proComingSoon: "Bientôt disponible — réservé aux praticiens partenaires",
    proNotifyEmail: "Être prévenu du lancement",
    userTabTitle: "Utilisateur",
    features: "Fonctionnalités",
    featurePhoto: "Détection par photo",
    featureGlucose: "Suivi glycémique",
    featureBarcode: "Scan des courses",
    featurePro: "Suivi par un diététicien",
    users: "utilisateurs",
    noDeficiencyData: "Pas assez de données sur 14 jours pour estimer les carences",
    scannerOpenCamera: "Ouvrir la caméra",
    scannerManualBarcode: "Saisir le code-barres manuellement",
    scannerScanBarcode: "Scanner le code-barres",
    cameraPermissionDenied: "Accès à la caméra refusé — utilisez la saisie manuelle",
    addedToJournal: "Ajouté au journal",
    scannerError: "Erreur de lecture du code-barres",
    serverUnavailable: "Serveur indisponible",
    connectingToServer: "Connexion au serveur en cours...",
    voiceSpeechNotSupported: "Reconnaissance vocale non disponible sur ce navigateur",
    scannerUnknownProduct: "Produit non reconnu",
    scannerChoiceManual: "Saisir le code manuellement",
    scannerLabelPhoto: "Photographier l'étiquette",
    scannerLabelPhotoHint: "L'IA lit le tableau nutritionnel",
    labelExtracted: "Valeurs extraites de l'étiquette",
    searching: "Recherche...",
    searchNoResults: "Aucun résultat",
    addToJournal: "Ajouter au journal",
    noFoodAdded: "Aucun aliment ajouté",
    moreItems: "de plus",
    showLess: "Voir moins",
    unknownFoodName: "Aliment inconnu",
    productNamePlaceholder: "Nom du produit",
    simulate: "Simuler",
    addToGroceries: "Ajouter aux courses",
    nutritionCalories: "Calories",
    nutritionSugarsSub: "dont Sucres",
    nutritionSaturatedSub: "dont Saturés",
    nutritionFiber: "Fibres",
    nutritionSugars: "Sucres",
    additiveCount: "additif(s)",
    nutritionPer100g: "g/100g",
    portionHalf: "1/2",
    portionNormal: "Normal",
    portionDouble: "Double",
    noEntriesYesterday: "Aucune entrée hier",
    analyzingBarcode: "Analyse du code-barres…",

    // ─── Radar vitamines & minéraux (REG-05) ───────────────────────────────
    vitaminMineralRadar: "Vitamines & Minéraux",
    improveIntake: "apports à améliorer",
    estimationBased: "Estimation basée sur {pct}% de vos aliments enregistrés (le reste n'a pas de données détaillées).",
    lowDataWarning: "Données insuffisantes pour estimer vos apports avec fiabilité.",
    radarDisclaimer: "Estimation indicative — ne remplace pas un bilan sanguin.",
  },
  ar: {
    journal: "اليومية",
    meals: "الوجبات",
    stats: "الإحصائيات",
    glucose: "السكر",
    settings: "الإعدادات",
    home: "الرئيسية",
    groceries: "التسوق",
    add: "إضافة",
    greeting: "مرحباً",
    streak: "أيام متتالية",
    remaining: "متبقية",
    over: "فوق الهدف",
    carbs: "كربوهيدرات",
    protein: "بروتين",
    fat: "دهون",
    weight: "الوزن",
    vsYesterday: "مقارنة بالأمس",
    todayMeals: "اليوم",
    hydration: "الترطيب",
    glasses: "أكواب",
    activity: "النشاط",
    stravaSource: "Strava",
    voice: "صوتي",
    photo: "صورة",
    scanner: "ماسح",
    favorites: "المفضلة",
    copyYesterday: "نسخ الأمس",
    breakfast: "الفطور",
    lunch: "الغداء",
    snack: "وجبة خفيفة",
    dinner: "العشاء",
    addFood: "إضافة",
    addMeal: "إضافة",
    recentFoods: "الأخيرة",
    detectByPhoto: "الذكاء الاصطناعي يكتشف الطبق",
    sayMeal: "أكلت...",
    barcode: "باركود",
    searchCiqual: "قاعدة CIQUAL",
    comingSoon: "قريباً",
    detectedAt: "\u062A\u0645 \u0627\u0643\u062A\u0634\u0627\u0641\u0647 \u0628\u0646\u0633\u0628\u0629",
    estimatedPortion: "الحصة المقدرة",
    ingredients: "المكونات",
    addToLunch: "إضافة إلى الغداء",
    searchFood: "ابحث عن طعام...",
    search: "بحث",
    recentlyAdded: "أضيف مؤخراً",
    all: "الكل",
    yourFavorites: "مفضلاتك",
    searchResults: "نتائج البحث",
    addToMeal: "أضف إلى",
    portion: "الحصة",
    customize: "تخصيص",
    today: "اليوم",
    days7: "7 أيام",
    days30: "30 يوم",
    year: "سنة",
    weekSummary: "ملخص الأسبوع",
    average: "المتوسط",
    bestDay: "أفضل يوم",
    hardestDay: "أصعب يوم",
    weightLost: "الوزن المفقود",
    muscleGained: "العضلات المكتسبة",
    fatLost: "الدهون",
    bodyFat: "نسبة الدهون",
    muscleMass: "كتلة عضلية",
    forbesEstimate: "تقدير بالمعادلة — لا يغني عن تحليل طبي",
    export: "تصدير",
    exportDone: "تم تنزيل التقرير",
    weightEvolution: "تطور الوزن",
    caloriesPerDay: "سعرات يومية",
    macroBreakdown: "توزيع الماكرو",
    glucoseSummary: "السكر",
    inTarget: "في الهدف",
    deficiencies: "نقص محتمل",
    deficiencyDisclaimer: "تقدير استرشادي — لا يغني عن تحليل الدم",
    probable: "محتمل",
    toMonitor: "يستحق المتابعة",
    insufficientGlucoseData: "بيانات غير كافية",
    glucoseTracking: "متابعة السكر",
    glucoseDisclaimer: "مؤشر اتجاه — لا يغني عن استشارة طبية",
    last14Days: "آخر 14 يوم",
    gmi: "GMI",
    estimatedHba1c: "HbA1c المقدر",
    tir: "TIR",
    targetRange: "70–180 mg/dL",
    cv: "CV",
    stability: "الاستقرار",
    stable: "مستقر",
    mean: "المتوسط",
    veryLow: "منخفض جداً",
    low: "منخفض",
    target: "الهدف",
    high: "مرتفع",
    veryHigh: "مرتفع جداً",
    addReading: "إضافة",
    importCsv: "استيراد LibreView",
    measurements: "قياسات",
    hypoAlert: "حلقة(حلقات) غلوكوز < 54 مج/دل مكتشفة",
    noGlucoseData: "لا توجد قياسات في هذه الفترة",
    addFirstReading: "إضافة قياس",
    fasting: "صائم",
    preMeal: "قبل الوجبة",
    postMeal: "بعد الوجبة",
    pontuelle: "عشوائية",
    contextStats: "متوسطات حسب السياق",
    periodLabel7d: "7 أيام",
    periodLabel14d: "14 يوم",
    periodLabel30d: "30 يوم",
    profile: "الملف الشخصي",
    edit: "تعديل",
    objective: "الهدف",
    recommended: "موصى به",
    units: "وحدات القياس",
    macroGoals: "أهداف الماكرو",
    appearance: "المظهر",
    darkMode: "الوضع الداكن",
    language: "اللغة",
    data: "البيانات",
    databaseSize: "حجم قاعدة البيانات",
    lastSync: "آخر مزامنة Strava",
    clearJournal: "مسح اليومية",
    clearWeight: "مسح بيانات الوزن",
    clearGlucose: "مسح بيانات السكر",
    exportData: "تصدير بياناتي (RGPD)",
    deleteAccount: "حذف حسابي",
    integrations: "التكاملات",
    connected: "متصل",
    notConnected: "غير متصل",
    disconnect: "قطع",
    notAvailable: "غير متوفر",
    about: "حول",
    privacyPolicy: "سياسة الخصوصية",
    legalNotice: "إشعار قانوني",
    rateApp: "قيّم التطبيق",
    healthGroup: "الصحة",
    glucoseTargetLabel: "هدف السكر",
    diabeticToggle: "أعاني من السكري",
    diabeticToggleHint: "يعرض وظائف الغلوكوز في التطبيق",
    confirmDelete: "تأكيد الحذف",
    irreversible: "هذا الإجراء لا رجعة منه.",
    deleteAccountConfirm: "هل أنت متأكد من حذف حسابك؟",
    saveProfile: "حفظ",
    profileEdit: "تعديل الملف",
    logout: "تسجيل الخروج",
    logoutTitle: "تسجيل الخروج؟",
    logoutDesc: "ستحتاج إلى تسجيل الدخول مرة أخرى للوصول إلى بياناتك.",
    clearAction: "مسح",
    loseWeight: "إنقاص الوزن",
    maintainWeight: "الحفاظ على الوزن",
    gainMuscle: "بناء العضلات",
    manageDiabetes: "إدارة السكري",
    speakNow: "تحدث الآن...",
    analyzing: "جاري التحليل...",
    serverWaking: "\u062C\u0627\u0631\u064A \u062A\u0634\u063A\u064A\u0644 \u0627\u0644\u062E\u0627\u062F\u0645...",
    offlineBanner: "\u063A\u064A\u0631 \u0645\u062A\u0635\u0644 \u2014 \u0628\u064A\u0627\u0646\u0627\u062A \u0645\u062D\u0644\u064A\u0629",
    loadingData: "\u062C\u0627\u0631\u064A \u0627\u0644\u062A\u062D\u0645\u064A\u0644...",
    retryLoad: "\u0625\u0639\u0627\u062F\u0629 \u0627\u0644\u0645\u062D\u0627\u0648\u0644\u0629",
    errorLoading: "\u062E\u0637\u0623 \u0641\u064A \u0627\u0644\u062A\u062D\u0645\u064A\u0644",
    scanProduct: "\u0645\u0633\u062D \u0645\u0646\u062A\u062C",
    detectedFoods: "\u0627\u0644\u0623\u0637\u0639\u0645\u0629 \u0627\u0644\u0645\u0643\u062A\u0634\u0641\u0629",
    cancel: "إلغاء",
    total: "المجموع",
    addActivity: "إضافة نشاط",
    duration: "المدة",
    caloriesBurned: "سعرات محروقة",
    activityType: "نوع النشاط",
    todayActivity: "نشاط اليوم",
    voiceActivity: "نشاط صوتي",
    speakActivity: "قل مثلاً: \"30 دقيقة جري\"",
    noActivity: "لم يُضَف أي نشاط",
    myGroceries: "مشترياتي",
    monthlyOverview: "ملخص الشهر",
    addedSugars: "سكريات مضافة",
    salt: "ملح",
    saturatedFat: "دهون مشبعة",
    vsOmsReference: "مقابل مرجع WHO",
    riskAdditives: "مضافات خطرة هذا الشهر",
    presentIn: "موجودة في",
    products: "منتجات",
    scannedProducts: "المنتجات الممسوحة",
    seeAlternatives: "عرض بدائل أصح",
    timesThisMonth: "×",
    excellent: "ممتاز",
    mediocre: "متوسط",
    bad: "سيئ",
    welcome: "مرحباً بك في NutriVita",
    tagline: "رفيقك الذكي للتغذية",
    getStarted: "ابدأ",
    tellUs: "أخبرنا عن نفسك",
    firstName: "الاسم الأول",
    age: "العمر",
    years: "سنة",
    sex: "الجنس",
    male: "ذكر",
    female: "أنثى",
    other: "آخر",
    height: "الطول",
    yourGoal: "هدفك",
    activityLevel: "مستوى النشاط",
    sedentary: "خامل",
    lightlyActive: "نشاط خفيف",
    moderatelyActive: "نشاط معتدل",
    veryActive: "نشاط عالي",
    extraActive: "نشاط مكثف",
    ready: "هيا بنا!",
    dailyGoal: "الهدف",
    perDay: "/يوم",
    startJourney: "ابدأ رحلتي",
    diabeticQuestion: "هل تتابع سكر الدم؟",
    diabeticYes: "نعم، أفعّل متابعة الغلوكوز",
    diabeticNo: "لا، تخطي هذه الخطوة",
    heroTitle: "افهم ما تأكل، بصورة واحدة",
    heroSubtitle: "صورة، صوت، سعرات، وزن، سكر ومشتريات",
    startFree: "ابدأ مجاناً",
    proSpace: "فضاء الطبيب",
    dataProtected: "بيانات محمية · RGPD",
    proTabTitle: "الفضاء المهني",
    proComingSoon: "قريباً",
    proNotifyEmail: "إعلامي بالإطلاق",
    userTabTitle: "مستخدم",
    features: "المميزات",
    featurePhoto: "كشف بالصورة",
    featureGlucose: "متابعة السكر",
    featureBarcode: "مسح المشتريات",
    featurePro: "متابعة بواسطة اختصاصي",
    users: "مستخدم",
    noDeficiencyData: "لا توجد بيانات كافية لتقدير النقص",
    scannerOpenCamera: "فتح الكاميرا",
    scannerManualBarcode: "إدخال الباركود يدوياً",
    scannerScanBarcode: "مسح الباركود",
    cameraPermissionDenied: "تم رفض الوصول إلى الكاميرا",
    addedToJournal: "تم الإضافة إلى اليومية",
    scannerError: "خطأ في قراءة الباركود",
    serverUnavailable: "الخادم غير متاح",
    connectingToServer: "جاري الاتصال بالخادم...",
    voiceSpeechNotSupported: "التعرف على الصوت غير مدعوم في هذا المتصفح",
    scannerUnknownProduct: "منتج غير معروف",
    scannerChoiceManual: "أدخل الرمز يدويًا",
    scannerLabelPhoto: "تصوير الملصق",
    scannerLabelPhotoHint: "الذكاء الاصطناعي يقرأ جدول القيم الغذائية",
    labelExtracted: "القيم المستخرجة من الملصق",
    searching: "جاري البحث...",
    searchNoResults: "لا توجد نتائج",
    addToJournal: "إضافة إلى اليومية",
    noFoodAdded: "لم يُضف أي طعام",
    moreItems: "آخرون",
    showLess: "عرض أقل",
    unknownFoodName: "منتج مجهول",
    productNamePlaceholder: "اسم المنتج",
    simulate: "محاكاة",
    addToGroceries: "أضف إلى المشتريات",
    nutritionCalories: "سعرات",
    nutritionSugarsSub: "منها سكريات",
    nutritionSaturatedSub: "منها مشبعة",
    nutritionFiber: "ألياف",
    nutritionSugars: "سكريات",
    additiveCount: "مضاف(ات)",
    nutritionPer100g: "غ/100غ",
    portionHalf: "1/2",
    portionNormal: "عادي",
    portionDouble: "ضعف",
    noEntriesYesterday: "\u0644\u0627 \u062A\u0648\u062C\u062F \u0625\u062F\u062E\u0627\u0644\u0627\u062A \u0623\u0645\u0633",
    analyzingBarcode: "\u062C\u0627\u0631\u064A \u062A\u062D\u0644\u064A\u0644 \u0627\u0644\u0631\u0645\u0632 \u0627\u0644\u0634\u0631\u064A\u0637\u064A\u2026",

    // \u2500\u2500\u2500 Radar vitamines & min\u00E9raux (REG-05) \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500
    vitaminMineralRadar: "\u0627\u0644\u0641\u064A\u062A\u0627\u0645\u064A\u0646\u0627\u062A \u0648\u0627\u0644\u0645\u0639\u0627\u062F\u0646",
    improveIntake: "\u064A\u062C\u0628 \u062A\u062D\u0633\u064A\u0646 \u0627\u0644\u0645\u062F\u062E\u0648\u0644\u0627\u062A",
    estimationBased: "\u062A\u0642\u062F\u064A\u0631 \u0628\u0646\u0627\u0621\u064B \u0639\u0644\u0649 {pct}% \u0645\u0646 \u0623\u063A\u0630\u064A\u062A\u0643 \u0627\u0644\u0645\u0633\u062C\u0644\u0629 (\u0627\u0644\u0628\u0627\u0642\u064A \u0644\u064A\u0633 \u0644\u062F\u064A\u0647 \u0628\u064A\u0627\u0646\u0627\u062A \u062A\u0641\u0635\u064A\u0644\u064A\u0629).",
    lowDataWarning: "\u0628\u064A\u0627\u0646\u0627\u062A \u063A\u064A\u0631 \u0643\u0627\u0641\u064A\u0629 \u0644\u062A\u0642\u062F\u064A\u0631 \u0645\u062F\u062E\u0648\u0644\u0627\u062A\u0643 \u0628\u0634\u0643\u0644 \u0645\u0648\u062B\u0648\u0642.",
    radarDisclaimer: "\u062A\u0642\u062F\u064A\u0631 \u0627\u0633\u062A\u0631\u0634\u0627\u062F\u064A \u2014 \u0644\u0627 \u064A\u063A\u0646\u064A \u0639\u0646 \u062A\u062D\u0644\u064A\u0644 \u0627\u0644\u062F\u0645.",
  },
  en: {
    journal: "Journal",
    meals: "Meals",
    stats: "Stats",
    glucose: "Glucose",
    settings: "Settings",
    home: "Home",
    groceries: "Groceries",
    add: "Add",
    greeting: "Hello",
    streak: "day streak",
    remaining: "remaining",
    over: "over",
    carbs: "Carbs",
    protein: "Protein",
    fat: "Fat",
    weight: "Weight",
    vsYesterday: "vs yesterday",
    todayMeals: "Today",
    hydration: "Hydration",
    glasses: "glasses",
    activity: "Activity",
    stravaSource: "Strava",
    voice: "Voice",
    photo: "Photo",
    scanner: "Scanner",
    favorites: "Favorites",
    copyYesterday: "Copy yesterday",
    breakfast: "Breakfast",
    lunch: "Lunch",
    snack: "Snack",
    dinner: "Dinner",
    addFood: "Add",
    addMeal: "Add",
    recentFoods: "Recent",
    detectByPhoto: "AI detects the dish",
    sayMeal: "I ate...",
    barcode: "Barcode",
    searchCiqual: "CIQUAL database",
    comingSoon: "Coming soon",
    detectedAt: "Detected at",
    estimatedPortion: "Estimated portion",
    ingredients: "Ingredients",
    addToLunch: "Add to lunch",
    searchFood: "Search for food...",
    search: "Search",
    recentlyAdded: "Recently added",
    all: "All",
    yourFavorites: "Your favorites",
    searchResults: "Results",
    addToMeal: "Add to",
    portion: "Portion",
    customize: "Customize",
    today: "Today",
    days7: "7 days",
    days30: "30 days",
    year: "Year",
    weekSummary: "Week summary",
    average: "Average",
    bestDay: "Best day",
    hardestDay: "Hardest day",
    weightLost: "Weight lost",
    muscleGained: "Muscle gained",
    fatLost: "Fat",
    bodyFat: "Body fat %",
    muscleMass: "Muscle mass",
    forbesEstimate: "Formula estimate — does not replace a medical analysis",
    export: "Export",
    exportDone: "Export downloaded",
    weightEvolution: "Weight evolution",
    caloriesPerDay: "Calories per day",
    macroBreakdown: "Macro breakdown",
    glucoseSummary: "Glucose",
    inTarget: "in target",
    deficiencies: "Potential deficiencies",
    deficiencyDisclaimer: "Indicative estimate — does not replace a blood test",
    probable: "Probable",
    toMonitor: "To monitor",
    insufficientGlucoseData: "Insufficient data",
    glucoseTracking: "Glucose",
    glucoseDisclaimer: "Trend indicator — does not replace medical advice",
    last14Days: "Last 14 days",
    gmi: "GMI",
    estimatedHba1c: "Estimated HbA1c",
    tir: "TIR",
    targetRange: "70–180 mg/dL",
    cv: "CV",
    stability: "Stability",
    stable: "Stable",
    mean: "Mean",
    veryLow: "Very low",
    low: "Low",
    target: "Target",
    high: "High",
    veryHigh: "Very high",
    addReading: "Add",
    importCsv: "Import LibreView",
    measurements: "measurements",
    hypoAlert: "episode(s) with glucose < 54 mg/dL detected in this period",
    noGlucoseData: "No readings in this period",
    addFirstReading: "Add a reading",
    fasting: "Fasting",
    preMeal: "Pre-meal",
    postMeal: "Post-meal",
    pontuelle: "Spot check",
    contextStats: "Averages by context",
    periodLabel7d: "7 days",
    periodLabel14d: "14 days",
    periodLabel30d: "30 days",
    profile: "Profile",
    edit: "Edit",
    objective: "Objective",
    recommended: "recommended",
    units: "Units",
    macroGoals: "Macro goals",
    appearance: "Appearance",
    darkMode: "Dark mode",
    language: "Language",
    data: "Data",
    databaseSize: "Database size",
    lastSync: "Last Strava sync",
    clearJournal: "Clear journal",
    clearWeight: "Clear weight data",
    clearGlucose: "Clear glucose data",
    exportData: "Export my data (GDPR)",
    deleteAccount: "Delete my account",
    integrations: "Integrations",
    connected: "Connected",
    notConnected: "Not connected",
    disconnect: "Disconnect",
    notAvailable: "Not available",
    about: "About",
    privacyPolicy: "Privacy policy",
    legalNotice: "Legal notice",
    rateApp: "Rate app",
    healthGroup: "Health",
    glucoseTargetLabel: "Glucose target",
    diabeticToggle: "I monitor my glucose",
    diabeticToggleHint: "Shows glucose features in the app",
    confirmDelete: "Confirm deletion",
    irreversible: "This action is irreversible.",
    deleteAccountConfirm: "Are you sure you want to delete your account? All data will be permanently deleted.",
    saveProfile: "Save",
    profileEdit: "Edit profile",
    logout: "Sign out",
    logoutTitle: "Sign out?",
    logoutDesc: "You will need to sign in again to access your data.",
    clearAction: "Clear",
    loseWeight: "Lose weight",
    maintainWeight: "Maintain weight",
    gainMuscle: "Build muscle",
    manageDiabetes: "Manage diabetes",
    speakNow: "Speak now...",
    analyzing: "Analyzing...",
    serverWaking: "Waking up server...",
    offlineBanner: "Offline — showing local data",
    loadingData: "Loading...",
    retryLoad: "Retry",
    errorLoading: "Loading error",
    scanProduct: "Scan a product",
    detectedFoods: "Detected foods",
    cancel: "Cancel",
    total: "Total",
    addActivity: "Add activity",
    duration: "Duration",
    caloriesBurned: "kcal burned",
    activityType: "Activity type",
    todayActivity: "Today's activity",
    voiceActivity: "Voice activity",
    speakActivity: "Say e.g.: \"30 minutes running\"",
    noActivity: "No activity added",
    myGroceries: "My groceries",
    monthlyOverview: "Monthly overview",
    addedSugars: "Added sugars",
    salt: "Salt",
    saturatedFat: "Saturated fat",
    vsOmsReference: "vs WHO reference",
    riskAdditives: "risk additive(s) this month",
    presentIn: "present in",
    products: "products",
    scannedProducts: "Scanned products",
    seeAlternatives: "See healthier alternatives",
    timesThisMonth: "×",
    excellent: "Excellent",
    mediocre: "Mediocre",
    bad: "Bad",
    welcome: "Welcome to NutriVita",
    tagline: "Your smart nutrition companion",
    getStarted: "Get started",
    tellUs: "Tell us about yourself",
    firstName: "First name",
    age: "Age",
    years: "years",
    sex: "Sex",
    male: "Male",
    female: "Female",
    other: "Other",
    height: "Height",
    yourGoal: "Your goal",
    activityLevel: "Activity level",
    sedentary: "Sedentary",
    lightlyActive: "Lightly active",
    moderatelyActive: "Moderately active",
    veryActive: "Very active",
    extraActive: "Extra active",
    ready: "Let's go!",
    dailyGoal: "Goal",
    perDay: "/day",
    startJourney: "Start my journey",
    diabeticQuestion: "Do you monitor your blood glucose?",
    diabeticYes: "Yes, enable glucose tracking",
    diabeticNo: "No, skip this step",
    heroTitle: "Understand what you eat, in one photo",
    heroSubtitle: "Photo, voice, calories, weight, glucose and groceries — in FR, عربي and EN",
    startFree: "Start for free",
    proSpace: "Healthcare space",
    dataProtected: "Protected data · GDPR",
    proTabTitle: "Healthcare space",
    proComingSoon: "Coming soon — reserved for partner practitioners",
    proNotifyEmail: "Be notified of launch",
    userTabTitle: "User",
    features: "Features",
    featurePhoto: "Photo detection",
    featureGlucose: "Glucose tracking",
    featureBarcode: "Grocery scanning",
    featurePro: "Dietician monitoring",
    users: "users",
    noDeficiencyData: "Not enough data over 14 days to estimate deficiencies",
    scannerOpenCamera: "Open camera",
    scannerManualBarcode: "Enter barcode manually",
    scannerScanBarcode: "Scan barcode",
    cameraPermissionDenied: "Camera access denied — use manual entry",
    addedToJournal: "Added to journal",
    scannerError: "Barcode read error",
    serverUnavailable: "Server unavailable",
    connectingToServer: "Connecting to server...",
    voiceSpeechNotSupported: "Speech recognition not available in this browser",
    scannerUnknownProduct: "Product not found",
    scannerChoiceManual: "Enter barcode manually",
    scannerLabelPhoto: "Photograph the label",
    scannerLabelPhotoHint: "AI reads the nutrition table",
    labelExtracted: "Values extracted from label",
    searching: "Searching...",
    searchNoResults: "No results",
    addToJournal: "Add to journal",
    noFoodAdded: "No food added yet",
    moreItems: "more",
    showLess: "Show less",
    unknownFoodName: "Unknown food",
    productNamePlaceholder: "Product name",
    simulate: "Simulate",
    addToGroceries: "Add to groceries",
    nutritionCalories: "Calories",
    nutritionSugarsSub: "incl. Sugars",
    nutritionSaturatedSub: "incl. Saturated",
    nutritionFiber: "Fiber",
    nutritionSugars: "Sugars",
    additiveCount: "additive(s)",
    nutritionPer100g: "g/100g",
    portionHalf: "1/2",
    portionNormal: "Normal",
    portionDouble: "Double",
    noEntriesYesterday: "No entries yesterday",
    analyzingBarcode: "Analyzing barcode…",

    // ─── Vitamins & minerals radar (REG-05) ────────────────────────────────
    vitaminMineralRadar: "Vitamins & Minerals",
    improveIntake: "intakes to improve",
    estimationBased: "Estimate based on {pct}% of your logged foods (the rest have no detailed data).",
    lowDataWarning: "Insufficient data to estimate your intakes reliably.",
    radarDisclaimer: "Indicative estimate — not a substitute for a blood test.",
  },
}

export type TranslationKey = keyof (typeof translations)["fr"]
